### ISSUE TITLE
gulp schema

### ISSUE THREAD

**Issue by zackify** [DNACodeStudios/supersonic#8]
after running gulp schema, which fails, this is the only error
<img width="781" alt="screen shot 2016-03-08 at 11 03 08 pm" src="https://cloud.githubusercontent.com/assets/449136/13625076/056169e0-e582-11e5-8254-295fc16cd983.png">

<img width="813" alt="screen shot 2016-03-08 at 11 04 33 pm" src="https://cloud.githubusercontent.com/assets/449136/13625095/244294ce-e582-11e5-920c-c0aaffae8f3e.png">

sorry for the horrible issue descriptions, but you told me to :P

**Comment by dphaener** [comment]
Fixed by https://github.com/DNACodeStudios/supersonic/commit/aaea94f7eeac5a204c5e0e8d9a4e49ec7926b577
